server:
  port: 8083

spring:
  application:
    name: cart-service

  datasource:
    url: jdbc:mysql://localhost:3306/cart_db
    username: root
    password: alpha

  jpa:
    hibernate:
      ddl-auto: validate

jwt:
  secret-key: 1234567890123456789012345678901234567890

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka